<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace Simple;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 响应结构
 *
 * Generated from protobuf message <code>simple.UserListResponse</code>
 */
class UserListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * repeated 重复(数组)
     *
     * Generated from protobuf field <code>repeated .simple.GetUserResponse list = 1;</code>
     */
    private $list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Simple\GetUserResponse[]|\Google\Protobuf\Internal\RepeatedField $list
     *           repeated 重复(数组)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     * repeated 重复(数组)
     *
     * Generated from protobuf field <code>repeated .simple.GetUserResponse list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * repeated 重复(数组)
     *
     * Generated from protobuf field <code>repeated .simple.GetUserResponse list = 1;</code>
     * @param \Simple\GetUserResponse[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Simple\GetUserResponse::class);
        $this->list = $arr;

        return $this;
    }

}

