<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

namespace Simple;

use UnexpectedValueException;

/**
 * 枚举类型第一个字段必须为 0
 *
 * Protobuf type <code>simple.UserSex</code>
 */
class UserSex
{
    /**
     * Generated from protobuf enum <code>MEN = 0;</code>
     */
    const MEN = 0;
    /**
     * Generated from protobuf enum <code>WOMEN = 1;</code>
     */
    const WOMEN = 1;

    private static $valueToName = [
        self::MEN => 'MEN',
        self::WOMEN => 'WOMEN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

