<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xuexitest.proto

namespace GPBMetadata;

class Xuexitest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aef010a0f7875657869746573742e70726f746f12097875657869746573" .
            "74221d0a0b5465737452657175657374120e0a0674797065696418012001" .
            "280322620a09546573745265706c7912300a0a6765746461746161727218" .
            "012003280b321c2e7875657869746573742e546573745265706c792e4765" .
            "74446174611a230a0747657444617461120a0a026964180120012803120c" .
            "0a046e616d6518022001280932460a0958756578697465737412390a0753" .
            "61795465737412162e7875657869746573742e5465737452657175657374" .
            "1a142e7875657869746573742e546573745265706c792200620670726f74" .
            "6f33"
        ));

        static::$is_initialized = true;
    }
}

