<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: xuexitest.proto

namespace Xuexitest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * <pre>
 *TestRequest 请求结构
 * </pre>
 *
 * Protobuf type <code>xuexitest.TestRequest</code>
 */
class TestRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 typeid = 1;</code>
     */
    private $typeid = 0;

    public function __construct() {
        \GPBMetadata\Xuexitest::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 typeid = 1;</code>
     */
    public function getTypeid()
    {
        return $this->typeid;
    }

    /**
     * <code>int64 typeid = 1;</code>
     */
    public function setTypeid($var)
    {
        GPBUtil::checkInt64($var);
        $this->typeid = $var;
    }

}

